# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-21 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_auto_20180321_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 17, 50, 49, 683403)),
        ),
    ]
